### ISSUE TITLE
Free water imaging and single-shell DTI

### ISSUE THREAD

**Issue by ElijahMak** [robbert-harms/MDT#16]
Hi again Robbert,

Many thanks for your help with the set up of MDT on my cluster some time ago. I have been obtaining some promising findings from the ODI maps and now I wish to study the free water maps. 

Can I confirm that the output of interest is "w_ic.w.nii.gz" ?

On a separate note, would you recommend using the NODDI-DTI model for single-shell data with b val 1000s)?

Thank you!

Best Wishes,
Elijah

**Comment by robbert-harms** [comment]
I don't know if you received my e-mail, therefore I post my e-mail here in the github comments.

-----------------------------

Hi Elijah,

Of course, I am glad I could be of help.

What exactly do you mean with the free water maps? The w_ic.w.nii.gz map you are referring to is the map with the volume fractions of the intra-cellular compartment. Do note, this is slightly different from the v_ic map in the NODDI toolbox due to small implementation differences. The v_ic map from the NODDI paper (Zhang 2012) is comparable to the NDI map from the MDT toolbox.

Maybe you are referring to the maps "NODDI_EC.d.nii.gz" and/or "NODDI_EC.dperp0.nii.gz"? These are, respectively, the parallel and the perpendicular diffusivities of the extra-cellular compartment model.

About your other question, the NODDI-DTI model is implemented as post-processing to the Tensor model, as specified in Edwards et al. 2017 (https://www.frontiersin.org/articles/10.3389/fnins.2017.00720/full). I would advice their recommendations on the matter. Having that said, in my experience NODDI-DTI seems to work well for b-values~1000.

Best wishes,

Robbert

**Comment by ElijahMak** [comment]
Hi Robbert

Happy New Year and I hope you have a good break. 

Yes, it does sound like the  EC maps would be the closest to what I am looking for.  Just to confirm again, I am looking for the output that is most equivalent to the ISO map provided by the NODDI Matlab Toolbox.

For reference, please see the following from this [paper](https://jnnp.bmj.com/content/90/4/404): "Data were analysed using the software distributed by the developers of NODDI (http://www.nitrc.org/projects/noddi_toolbox), implemented in Matlab (V.2012b), which yielded maps of the neurite density index (NDI), orientation dispersion index (ODI) and free water volume fraction for each participant (isotropic compartment (ISO)).

Appreciate your time.

Best Wishes,
Elijah

**Comment by robbert-harms** [comment]
Hi Elijah,

Happy new year to you as well. Thank you for asking, I had a nice break indeed. How was your holiday?

Considering the reference you sent me, the map you are looking for is the w_csf.w map from MDT. That is, the isotropic compartment (ISO) map is called w_csf.w in MDT.

Best wishes,

Robbert

**Comment by ElijahMak** [comment]
Hi Robbert,

That’s brilliant, thanks very much. May I have your email as well? I wish to discuss a potential collaboration if you are interested.

Best Wishes,
Elijah

Dr. Elijah Mak
Alzheimer’s Society Junior Research Fellow
Department of Psychiatry
Old Age Psychiatry Group
University of Cambridge
http://www.neuroscience.cam.ac.uk/directory/profile.php?fkm24

On 9 Jan 2020, 11:28 +0000, Robbert Harms <notifications@github.com>, wrote:

Hi Elijah,

Happy new year to you as well. Thank you for asking, I had a nice break indeed. How was your holiday?

Considering the reference you sent me, the map you are looking for is the w_csf.w map from MDT. That is, the isotropic compartment (ISO) map is called w_csf.w in MDT.

Best wishes,

Robbert

**Comment by robbert-harms** [comment]
Hi Elijah,

Of course, I am always interested to hear about a possible collaboration. You can reach me at robbert@xkls.nl. 

Please do send me an e-mail, then I'll remove my address from this site to prevent spam.

With best wishes,

Robbert
