### ISSUE TITLE
Agreement between MDT and Matlab Toolbox

### ISSUE THREAD

**Issue by Croall** [robbert-harms/MDT#24]
Hi,

I'm processing a fairly large dataset of DWI images, so the GPU acceleration that MDT offers is very desirable compared to the Matlab toolbox. Before going ahead with everything though, I'm trying to get results between the two in mathematically-complete agreement so I can be confident what I'm doing is exactly what I'm intending to!

I am using the current version of the NODDI Matlab toolbox, with all default settings. With this I've processed a whole-brain DWI scan.

On the MDT side of things, have run the current MDT version with the "NODDI" model on the same data. Checking between ODI outputs, initially the results were similar though somewhat different in areas of brain tissue, and very markedly different in areas of CSF where MDT appeared to almost-zero those voxels while the Matlab toolbox assigned very high values. I came across this previous thread on github seeming to cover the same issue - https://github.com/robbert-harms/MDT/issues?q=is%3Aissue+is%3Aclosed

I followed that advice, setting the noise stdev value to "1", and reran the model. In brain tissue the results are now much more similar, to the point where you might not notice they're different to look at, but on inspection the values still differ. However values are still marginally divergent.  e.g. picking a random voxel from the corpus callosum, MDT gives 0.562... while Matlab gives 0.566...

I realise this doesn't necessarily invalidate any of the data, but it would be reassuring to achieve an exact match before proceeding with the main analysis. If any advice could be offered on further settings etc. that could be adjusting to bring it all in line that would be very appreciated!

Thank you very much in advance,
Iain

**Comment by robbert-harms** [comment]
Hi Iain, 

Thank you for considering MDT for your computations. 

I think an _exact_ match may be difficult to achieve, and maybe also not the right question to ask. 

First let me get to why an exact match is difficult to achieve. Both Matlab and MDT use finite precision data types, which, due to round-off errors typically result in small differences in output. Also, optimization routines are considered numerically unstable, meaning that small differences in input may result in larger differences in output. In addition, even if you would stay within Matlab, small differences in the NODDI model implementation will most likely result in different outcomes. 

Next to that, an absolute match may not be that interesting. For example, it is nowhere sure that the Matlab results are the true results. One way to check the difference in quality of different results is to compare the difference in (log-)likelihood. The log-likelihood is, after all, the metric used by the optimization routines to quantify the quality of the optimization. In my results, back in the day, MDT typically outperformed the Matlab toolbox on this metric. That is, given the same data, MDT and Matlab provided me with slightly different outcomes, of which the MDT results gave the overall higher likelihood. 

Another point to take into consideration is the notion of uncertainty, which is the topic of my next article. The main takeaway is that the estimated model parameters each have an uncertainty around it, which can be marginalized and expressed as a standard deviation. This standard deviation tries to express how much faith we should place in the results and is heavily dependent on the quality of the data. More and better data lead to a lower uncertainty, and vice versa. In my experience, the standard deviation is typically larger than the differences in results between the various software implementations. For example, if the uncertainty in ODI is 0.05, a difference in results of 0.562 vs 0.566 is meaningless as it falls completely in the uncertainty we have around our computations.

If you want to dig deeper, MDT offers a way to estimate the uncertainty around your parameter estimates using the theory of the Fisher Information Matrix (basically the inverse of the Hessian provides a covariance matrix). If you use the Python API, it can be enabled by adding a `post_processing` keyword as:
```python
mdt.fit_model('NODDI', ..., post_processing={'uncertainties': True})
```

I hope this was of any use to you. I am curious to your thoughts on the above.

Best wishes,

Robbert

**Comment by Croall** [comment]
Dear Robbert,

I am not a computer scientist in my background, so had been assuming there were probably various reasons buried in how the code is executed (none of which would affect the overall validity of any model fitting) why maps from MDT and the Matlab toolbox may differ marginally. My reasons for posting here were mainly so I could be in a position where I could understand these discrepancies as much as possible before proceeding with a larger analysis, and your post was very helpful with that. 

Thanks very much for your time in writing out your detailed reply,
All the best,
Iain
